#!/bin/bash
#
# just ignore all shit files after `git pull`
#

# you should concatenate cat conf.sh lib.sh <this> | tee hook

mkdir -p $BACKUP_DIR
mv ${IGNORED_FILES[@]} $BACKUP_DIR 2> /dev/null || true
dot update-index --assume-unchanged ${IGNORED_FILES[@]}
