:nnoremap ,gs :Gstatus<CR>
:nnoremap ,gc :Gcommit<CR>
:nnoremap ,gm :Gmerge<CR>
:nnoremap ,gpl :Gpull<CR>
:nnoremap ,gps :Gpush<CR>
:nnoremap ,gf :Gfetch<CR>
:nnoremap ,ge :Gedit<CR>
:nnoremap ,gsp :Gsplit<CR>
:nnoremap ,gvs :Gvsplit<CR>
:nnoremap ,gr :Gread<CR>
:nnoremap ,gw :Gwrite<CR>
:nnoremap ,gd :Gdiff<CR>
:nnoremap ,grm :Gremove<CR>
:nnoremap ,gpu :'<,'>diffput<CR>
:nnoremap ,gup :diffupdate<CR>
