#!/bin/bash

#
# =>     Script for install conky custom scripts 
#
# ===>      With network adress fix for manjaro
#
# =====>     Copyright © Manoel Vilela
#

# verify the user it's root
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

files=('conky-startup' 'conky-update-network' 'get-network')


function link-files {
    f=$1
    x=0
    while [ $x -lt ${#f[@]} ] 
    do
        link=${f[$x]}
        new_path=`pwd`/$link
        final=/usr/bin/$link
        sudo ln -s -v $new $final
        sudo chmod +x -v $final
        let "x = x + 1" 
    done
}

# autostart function for conky script files
function auto-start {
    entry="""[Desktop Entry]\n\
Encoding=UTF-8\n\
Version=0.9.4\n\
Type=Application\n\
Name=Conky Startup\n\
Comment=Start all my conkys\n\
Exec=conky-startup\n\
OnlyShowIn=XFCE;\n\
StartupNotify=false\n\
Terminal=false\n\
Hidden=false\n"""
    printf $entry > ~/.config/autostart/conky-startup.desktop
    echo "Created a entry startup conky on ~/.config/autostart/"
}

# Main program
echo 'Linking files...'
link-files
echo 'Setup the configuration for conky startup with the system'
auto-start
echo 'Every finished! Try reboot the system or call "conky-startup" on terminal'
